services:
  - type: web
    name: naol-links-portfolio
    env: static
    buildCommand: ""
    startCommand: "npx http-server -p $PORT --cors"
    staticPublishPath: .
    routes:
      - path: /
        destination: naol-links.html
